resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: configmap-with-envvariables
    envs:
      - myconfigmap.properties
  - name: configmap-with-files
    envs:
      - myconfigmap.properties
  - name: configmap-with-literals
    literals:
      - myvar1=20
      - mystr1=dvstech

secretGenerator:
  - name: secret-with-envvariables
    envs:
      - secret.txt
  - name: secret-with-files
    envs:
      - secret.txt
  - name: secret-with-literals
    literals:
      - myvar1=20
      - mystr1=dvstech

generatorOptions:
  disableNameSuffixHash: true
namespace: my-namespace
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  app: bingo
commonAnnotations:
  oncallPager: 800-555-1212  
patchesStrategicMerge:
- increase_replicas.yaml
- set_memory.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-nginx
  path: patch.yaml